[programs.mainnet]
distribution = "2YkXmCtRc6BzST3eavg7pxnYRJmoMBXEB8pzDN77wuhN"
[programs.devnet]
distribution = "2YkXmCtRc6BzST3eavg7pxnYRJmoMBXEB8pzDN77wuhN"

[registry]
url = "https://github.com/0xTan1319"

[provider]
cluster = "localnet"
wallet = "../key/uu.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
